### ISSUE TITLE
Fatal Error when using

### ISSUE THREAD

**Issue by rupreck** [Soloplan/resharper-clt-plugin#12]
Hello,

The following error occurs using this plugin when the MSBuild Scanner end step is run.

`[1] - 08:54:17.478 ERROR: Error during SonarScanner execution
[2] - java.nio.file.InvalidPathException: Illegal char <:> at index 29: S:\s\48518\PAP\xxx.git\S:\s\48518\PAP\xxx.git\Refactoring\yyy.zzz.DataBehaviour\yyy.zzz.DataBehaviour\Query\ProviderServices\entity\GetDetailsQuery.cs
[3] - at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
[4] - at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
[5] - at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
[6] - at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
[7] - at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
[8] - at java.base/java.io.File.toPath(File.java:2290)
[9] - at org.sonar.api.scan.filesystem.PathResolver.relativePath(PathResolver.java:121)
[10] - at org.sonar.api.batch.fs.internal.predicates.AbsolutePathPredicate.get(AbsolutePathPredicate.java:51)
[11] - at org.sonar.api.batch.fs.internal.DefaultFileSystem.inputFiles(DefaultFileSystem.java:138)
[12] - at org.sonar.api.batch.fs.internal.DefaultFileSystem.inputFile(DefaultFileSystem.java:108)
[13] - at com.soloplan.oss.sonarqube.plugin.resharper.clt.sensors.BaseSensor.execute(BaseSensor.java:191)
[14] - at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
[15] - at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
[16] - at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
[17] - at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
[18] - at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
[19] - at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:79)
[20] - at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
[21] - at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[22] - at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:384)
[23] - at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:380)
[24] - at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:377)
[25] - at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:349)
[26] - at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
[27] - at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[28] - at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:136)
[29] - at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
[30] - at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
[31] - at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
[32] - at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
[33] - at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
[34] - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[35] - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[36] - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[37] - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[38] - at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[39] - at com.sun.proxy.$Proxy0.execute(Unknown Source)
[40] - at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
[41] - at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
[42] - at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
[43] - at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
[44] - at org.sonarsource.scanner.cli.Main.main(Main.java:61)
[45] - The SonarScanner did not complete successfully
[46] - 08:54:17.556  Post-processing failed. Exit code: 1
`
It appears to be concatenating a path and a path+filename as path+path+filename

Is there a solution or workaround?

Will

**Comment by rupreck** [comment]
The issue appears to be the one reported here:

[https://community.sonarsource.com/t/java-nio-file-invalidpathexception-illegal-char-at-exception/23203](https://community.sonarsource.com/t/java-nio-file-invalidpathexception-illegal-char-at-exception/23203)

**Comment by rupreck** [comment]
This is resolved by using a relative reference to the solution file.  Absolute paths do not seem to be supported.
